# db/seeds.rb

foods = [
  { food_name: "大根", category_id: 1, start_week: 48, end_week: 8, most_product_week: 2, is_rare: false, image: "", recommend_week: nil },
  { food_name: "白菜", category_id: 1, start_week: 48, end_week: 8, most_product_week: 3, is_rare: false, image: "", recommend_week: nil },
  { food_name: "春菊", category_id: 1, start_week: 48, end_week: 8, most_product_week: 2, is_rare: false, image: "", recommend_week: nil },
  { food_name: "長ネギ", category_id: 1, start_week: 48, end_week: 8, most_product_week: 4, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ほうれん草", category_id: 1, start_week: 48, end_week: 8, most_product_week: 1, is_rare: false, image: "", recommend_week: nil },
  { food_name: "里芋", category_id: 1, start_week: 48, end_week: 6, most_product_week: 2, is_rare: false, image: "", recommend_week: nil },
  { food_name: "金時人参", category_id: 1, start_week: 48, end_week: 4, most_product_week: 1, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ブリ", category_id: 2, start_week: 48, end_week: 4, most_product_week: 1, is_rare: false, image: "", recommend_week: nil },
  { food_name: "タラ", category_id: 2, start_week: 48, end_week: 6, most_product_week: 3, is_rare: false, image: "", recommend_week: nil },
  { food_name: "カキ", category_id: 2, start_week: 48, end_week: 6, most_product_week: 2, is_rare: false, image: "", recommend_week: nil },
  { food_name: "アンコウ", category_id: 2, start_week: 48, end_week: 6, most_product_week: 2, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ハッカク", category_id: 2, start_week: 48, end_week: 4, most_product_week: 1, is_rare: true, image: "https://hokkaido-hyakka.com/wp/wp-content/uploads/2025/02/22347995_s.jpg", recommend_week: 48 },
  { food_name: "シマエビ", category_id: 2, start_week: 48, end_week: 6, most_product_week: 2, is_rare: true, image: "https://img.hachimenroppi.com/image.php?f=CZRhnELO&adir=topic_part&id=6211", recommend_week: 49 },
  { food_name: "鮟鱇の肝（あん肝）", category_id: 2, start_week: 48, end_week: 6, most_product_week: 3, is_rare: true, image: "https://umai-mon.shokubunka.co.jp/blog/wp-content/uploads/2015/12/ATM1139.jpg", recommend_week: 52 },
  { food_name: "レンコン", category_id: 1, start_week: 48, end_week: 6, most_product_week: 2, is_rare: false, image: "", recommend_week: nil },
  { food_name: "菜の花", category_id: 1, start_week: 6, end_week: 8, most_product_week: 7, is_rare: false, image: "", recommend_week: nil },
  { food_name: "イチゴ", category_id: 3, start_week: 2, end_week: 8, most_product_week: 5, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ミカン", category_id: 3, start_week: 48, end_week: 6, most_product_week: 2, is_rare: false, image: "", recommend_week: nil },
  { food_name: "キンカン", category_id: 3, start_week: 2, end_week: 6, most_product_week: 4, is_rare: true, image: "https://life.ja-group.jp/upload/food/vegetable/main/94_1.jpg", recommend_week: 2 },
  { food_name: "ユズ", category_id: 2, start_week: 48, end_week: 4, most_product_week: 1, is_rare: false, image: "", recommend_week: nil },
  { food_name: "フキノトウ", category_id: 1, start_week: 7, end_week: 8, most_product_week: 8, is_rare: true, image: "https://www.i-nekko.jp/pixta_13919717_S.jpg", recommend_week: 7 },
  { food_name: "ズワイガニ", category_id: 2, start_week: 48, end_week: 6, most_product_week: 3, is_rare: false, image: "", recommend_week: nil },
  { food_name: "毛ガニ", category_id: 2, start_week: 48, end_week: 6, most_product_week: 3, is_rare: false, image: "", recommend_week: nil },
  { food_name: "タチウオ（冬タチ）", category_id: 2, start_week: 48, end_week: 4, most_product_week: 2, is_rare: true, image: "https://hyoki.jp/cms/wp-content/uploads/2018/12/pixta_35646067_S.jpg", recommend_week: 50 },
  { food_name: "春キャベツ", category_id: 1, start_week: 10, end_week: 18, most_product_week: 12, is_rare: false, image: "", recommend_week: nil },
  { food_name: "新玉ねぎ", category_id: 1, start_week: 10, end_week: 20, most_product_week: 14, is_rare: false, image: "", recommend_week: nil },
  { food_name: "たけのこ (筍)", category_id: 1, start_week: 14, end_week: 22, most_product_week: 16, is_rare: false, image: "", recommend_week: nil },
  { food_name: "アスパラガス", category_id: 1, start_week: 12, end_week: 22, most_product_week: 16, is_rare: false, image: "", recommend_week: nil },
  { food_name: "グリーンピース", category_id: 1, start_week: 12, end_week: 20, most_product_week: 14, is_rare: false, image: "", recommend_week: nil },
  { food_name: "キャベツ", category_id: 1, start_week: 8, end_week: 16, most_product_week: 10, is_rare: false, image: "", recommend_week: nil },
  { food_name: "そら豆", category_id: 1, start_week: 14, end_week: 22, most_product_week: 18, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ウド", category_id: 1, start_week: 10, end_week: 16, most_product_week: 12, is_rare: true, image: "https://hyoki.jp/cms/wp-content/uploads/2019/04/1-2.jpg", recommend_week: 10 },
  { food_name: "ワラビ", category_id: 1, start_week: 14, end_week: 20, most_product_week: 16, is_rare: true, image: "https://life.ja-group.jp/upload/food/vegetable/main/116_1.jpg", recommend_week: 14 },
  { food_name: "タイ (真鯛)", category_id: 2, start_week: 10, end_week: 18, most_product_week: 14, is_rare: false, image: "", recommend_week: nil },
  { food_name: "サワラ", category_id: 2, start_week: 10, end_week: 20, most_product_week: 14, is_rare: false, image: "", recommend_week: nil },
  { food_name: "マアジ", category_id: 2, start_week: 14, end_week: 22, most_product_week: 18, is_rare: false, image: "", recommend_week: nil },
  { food_name: "メバル", category_id: 2, start_week: 12, end_week: 20, most_product_week: 14, is_rare: false, image: "", recommend_week: nil },
  { food_name: "サヨリ", category_id: 2, start_week: 12, end_week: 18, most_product_week: 14, is_rare: true, image: "http://www.ikgyoren.jf-net.ne.jp/img/rp/f_sayori.jpg", recommend_week: 12 },
  { food_name: "ニシン", category_id: 2, start_week: 10, end_week: 16, most_product_week: 12, is_rare: false, image: "", recommend_week: nil },
  { food_name: "シラス", category_id: 2, start_week: 12, end_week: 22, most_product_week: 16, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ホウボウ", category_id: 2, start_week: 10, end_week: 18, most_product_week: 14, is_rare: true, image: "https://www.hyponex.co.jp/yasai_daijiten/websys/wp-content/uploads/2021/01/%E3%83%9B%E3%82%A6%E3%83%9C%E3%82%A6D-770x475.jpg", recommend_week: 11 },
  { food_name: "トマト", category_id: 1, start_week: 22, end_week: 34, most_product_week: 28, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ナス", category_id: 1, start_week: 22, end_week: 32, most_product_week: 28, is_rare: false, image: "", recommend_week: nil },
  { food_name: "キュウリ", category_id: 1, start_week: 22, end_week: 32, most_product_week: 28, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ピーマン", category_id: 1, start_week: 22, end_week: 34, most_product_week: 28, is_rare: false, image: "", recommend_week: nil },
  { food_name: "オクラ", category_id: 1, start_week: 24, end_week: 34, most_product_week: 30, is_rare: false, image: "", recommend_week: nil },
  { food_name: "モロヘイヤ", category_id: 1, start_week: 26, end_week: 34, most_product_week: 30, is_rare: false, image: "", recommend_week: nil },
  { food_name: "枝豆", category_id: 1, start_week: 28, end_week: 34, most_product_week: 32, is_rare: false, image: "", recommend_week: nil },
  { food_name: "スイカ", category_id: 1, start_week: 28, end_week: 34, most_product_week: 32, is_rare: false, image: "", recommend_week: nil },
  { food_name: "メロン", category_id: 1, start_week: 28, end_week: 34, most_product_week: 32, is_rare: false, image: "", recommend_week: nil },
  { food_name: "トウモロコシ", category_id: 1, start_week: 24, end_week: 32, most_product_week: 28, is_rare: false, image: "", recommend_week: nil },
  { food_name: "キウイ", category_id: 3, start_week: 24, end_week: 32, most_product_week: 28, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ナツメ", category_id: 1, start_week: 26, end_week: 32, most_product_week: 30, is_rare: true, image: "https://media.delishkitchen.tv/article/2529/14ae5ai80e1h.jpeg?version=1751434212", recommend_week: 26 },
  { food_name: "ハモ", category_id: 2, start_week: 26, end_week: 32, most_product_week: 30, is_rare: true, image: "https://kappo-aun.jp/wp-content/uploads/2020/06/AdobeStock_87191418-592x410.jpeg", recommend_week: 27 },
  { food_name: "サンマ", category_id: 2, start_week: 28, end_week: 34, most_product_week: 32, is_rare: false, image: "", recommend_week: nil },
  { food_name: "カツオ", category_id: 2, start_week: 24, end_week: 32, most_product_week: 28, is_rare: false, image: "", recommend_week: nil },
  { food_name: "マグロ", category_id: 2, start_week: 24, end_week: 34, most_product_week: 30, is_rare: false, image: "", recommend_week: nil },
  { food_name: "イサキ", category_id: 2, start_week: 22, end_week: 30, most_product_week: 26, is_rare: true, image: "https://video.kurashiru.com/production/articles/463bca99-8f99-4368-bccd-4ff669be6f6b/wide_thumbnail_normal.jpg?1723017220", recommend_week: 22 },
  { food_name: "シロギス", category_id: 2, start_week: 24, end_week: 32, most_product_week: 28, is_rare: true, image: "https://img.hachimenroppi.com/image.php?f=CZ8xVZdH&adir=topic&id=835", recommend_week: 24 },
  { food_name: "マダコ", category_id: 2, start_week: 45, end_week: 5, most_product_week: 50, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ミズダコ", category_id: 2, start_week: 49, end_week: 5, most_product_week: 2, is_rare: false, image: "", recommend_week: nil },
  { food_name: "サツマイモ", category_id: 1, start_week: 36, end_week: 47, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "かぼちゃ", category_id: 1, start_week: 36, end_week: 46, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "長ネギ", category_id: 1, start_week: 36, end_week: 47, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "しめじ", category_id: 1, start_week: 36, end_week: 46, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "えのき茸", category_id: 1, start_week: 36, end_week: 46, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "まいたけ", category_id: 1, start_week: 36, end_week: 46, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ぶどう", category_id: 3, start_week: 36, end_week: 44, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "なし", category_id: 3, start_week: 36, end_week: 44, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "りんご", category_id: 3, start_week: 38, end_week: 46, most_product_week: 42, is_rare: false, image: "", recommend_week: nil },
  { food_name: "栗", category_id: 3, start_week: 36, end_week: 44, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "サンマ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "サバ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "イワシ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "アジ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "サケ", category_id: 2, start_week: 38, end_week: 46, most_product_week: 42, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ムラサキイモ", category_id: 1, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "https://www.kagome.co.jp/library/vegeday/img/vegetables/img_purpleyam_main.jpg", recommend_week: 36 },
  { food_name: "マツタケ", category_id: 1, start_week: 40, end_week: 44, most_product_week: 42, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ギンナン", category_id: 1, start_week: 36, end_week: 42, most_product_week: 38, is_rare: true, image: "https://life.ja-group.jp/upload/food/vegetable/main/115_1.jpg", recommend_week: 37 },
  { food_name: "コウタケ", category_id: 1, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "", recommend_week: nil },
  { food_name: "アケビ", category_id: 3, start_week: 36, end_week: 42, most_product_week: 38, is_rare: true, image: "https://storage.tenki.jp/storage/static-images/suppl/article/image/2/25/255/25541/2/large.jpg", recommend_week: 39 },
  { food_name: "ハタハタ", category_id: 2, start_week: 36, end_week: 42, most_product_week: 38, is_rare: true, image: "https://media.delishkitchen.tv/article/1317/qtq0q93sg3.jpeg?version=1652061190", recommend_week: 40 },
  { food_name: "カワハギ", category_id: 2, start_week: 36, end_week: 42, most_product_week: 38, is_rare: true, image: "https://sakushima.com/sakupress/wp-content/uploads/a181a90fc1d0f58553a002fbd366d697.jpg", recommend_week: 41 },
  { food_name: "ヒラメ (真ヒラメ)", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "シラウオ", category_id: 2, start_week: 36, end_week: 42, most_product_week: 38, is_rare: true, image: "", recommend_week: nil },
  { food_name: "トビウオ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "https://umito.maruha-nichiro.co.jp/wpumito/wp-content/uploads/2021/04/93img01.jpg", recommend_week: 42 },
  { food_name: "ウチワエビ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "https://cdn.macaro-ni.jp/image/summary/57/57532/df6db71e16ec9991d76bef1bf3270dcd.jpg", recommend_week: 43 },
  { food_name: "コチ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "https://tshop.r10s.jp/sinsenuotakamaru/cabinet/03372140/img63782158.jpg?fitin=720%3A720", recommend_week: 44 },
  { food_name: "ノドグロ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "", recommend_week: nil },
  { food_name: "アイナメ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "", recommend_week: nil },
  { food_name: "ハゼ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "https://funabashi-ichiba.jp/wp-content/uploads/2019/10/P1060263-630x473.jpg", recommend_week: 38 },
  { food_name: "シロサケ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "", recommend_week: nil },
  { food_name: "クマエビ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "", recommend_week: nil },
  { food_name: "ホッケ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "イシダイ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "", recommend_week: nil },
  { food_name: "アマダイ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "", recommend_week: nil },
  { food_name: "アオリイカ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "スズキ", category_id: 2, start_week: 36, end_week: 44, most_product_week: 40, is_rare: true, image: "", recommend_week: nil }
  { food_name: "セリ", category_id: 1, start_week: 1, end_week: 5, most_product_week: 3, is_rare: true, image: "https://hyoki.jp/cms/wp-content/uploads/2017/02/pixta_15450193_M.jpg", recommend_week: 1 },
  { food_name: "ハマグリ", category_id: 2, start_week: 2, end_week: 6, most_product_week: 3, is_rare: false, image: "", recommend_week: nil },
  { food_name: "キンメダイ", category_id: 2, start_week: 3, end_week: 5, most_product_week: 4, is_rare: true, image: "https://www.kamaboko.com/assets/shohin/img/agetai_column_01.jpg", recommend_week: 4 },
  { food_name: "ワカメ", category_id: 2, start_week: 4, end_week: 8, most_product_week: 5, is_rare: false, image: "", recommend_week: nil },
  { food_name: "アユ", category_id: 2, start_week: 12, end_week: 15, most_product_week: 13, is_rare: true, image: "https://kappo-aun.jp/wp-content/uploads/2020/06/AdobeStock_158263074-scaled.jpeg", recommend_week: 13 },
  { food_name: "ホヤ", category_id: 2, start_week: 14, end_week: 17, most_product_week: 15, is_rare: true, image: "https://www.umai-aomori.jp/lsc/upfile/article/0000/0132/132_1_l.jpg", recommend_week: 15 },
  { food_name: "スズキ", category_id: 2, start_week: 15, end_week: 18, most_product_week: 16, is_rare: false, image: "", recommend_week: nil },
  { food_name: "アカイカ", category_id: 2, start_week: 18, end_week: 21, most_product_week: 19, is_rare: true, image: "https://kawamotoya.co.jp/store/wp-content/uploads/2020/10/akaika-3.jpg", recommend_week: 19 },
  { food_name: "ハスイモ（ズイキ）", category_id: 1, start_week: 19, end_week: 22, most_product_week: 20, is_rare: true, image: "https://media.delishkitchen.tv/article/1341/04jzu21994gj.jpeg?version=1643356761", recommend_week: 20 },
  { food_name: "イチジク", category_id: 3, start_week: 20, end_week: 24, most_product_week: 21, is_rare: true, image: "https://media.delishkitchen.tv/article/944/x5wa3gkjct.jpeg?version=1750408648", recommend_week: 21 },
  { food_name: "キス", category_id: 2, start_week: 22, end_week: 25, most_product_week: 23, is_rare: true, image: "https://www.kasumiya.jp/pic-labo/kisu_maruboshi_gift.jpg", recommend_week: 23 },
  { food_name: "マナガツオ", category_id: 2, start_week: 27, end_week: 30, most_product_week: 28, is_rare: true, image: "https://hyoki.jp/cms/wp-content/uploads/2019/03/1-24.jpg", recommend_week: 28 },
  { food_name: "ハグラウリ", category_id: 1, start_week: 29, end_week: 32, most_product_week: 30, is_rare: true, image: "https://www.photolibrary.jp/mhd1/img465/450-20160516124718161799.jpg", recommend_week: 30 },
  { food_name: "マコモダケ", category_id: 1, start_week: 30, end_week: 34, most_product_week: 31, is_rare: true, image: "https://media.delishkitchen.tv/article/2821/tucgkrxwkn8.jpeg?version=1751358677", recommend_week: 31 },
  { food_name: "カマス", category_id: 2, start_week: 31, end_week: 34, most_product_week: 32, is_rare: true, image: "https://video.kurashiru.com/production/articles/9373efbd-4c97-4298-9a35-cbbb58ff042a/wide_thumbnail_normal.jpg?1753160651", recommend_week: 32 },
  { food_name: "サワラ", category_id: 2, start_week: 32, end_week: 35, most_product_week: 33, is_rare: false, image: "", recommend_week: nil },
  { food_name: "きゅうりメロン", category_id: 1, start_week: 28, end_week: 37, most_product_week: 34, is_rare: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg0LegXlHSG3Dk3fV2gHDxugVyHh8CXiIJ_3f5MXQH5fYKn7wwd52VepfcLsbftlpqDg8&usqp=CAU", recommend_week: 34 },
  { food_name: "キクイモ", category_id: 1, start_week: 46, end_week: 10, most_product_week: 50, is_rare: true, image: "https://life.ja-group.jp/upload/food/vegetable/main/121_1.jpg", recommend_week: 6 },
  { food_name: "スベリヒユ", category_id: 1, start_week: 37, end_week: 40, most_product_week: 38, is_rare: true, image: "", recommend_week: nil },
  { food_name: "ドングリ（食用）", category_id: 3, start_week: 44, end_week: 47, most_product_week: 45, is_rare: true, image: "https://cdn.macaro-ni.jp/assets/img/shutterstock/shutterstock_234487867.jpg?p=small", recommend_week: 45 },
  { food_name: "ナガスクジラ尾の身", category_id: 2, start_week: 45, end_week: 48, most_product_week: 46, is_rare: true, image: "https://www.simetani.com/shohin_photo/a1311-big.jpg", recommend_week: 46 },
  { food_name: "ユリネ", category_id: 1, start_week: 46, end_week: 49, most_product_week: 47, is_rare: true, image: "https://www.shizensyokuhin.jp/archives/uploads/content/image/22719/001(2).jpg", recommend_week: 47 },
  { food_name: "カラスミ（ボラ卵巣）", category_id: 2, start_week: 50, end_week: 52, most_product_week: 51, is_rare: true, image: "https://umai-mon.b-cdn.net/user/images/pg/2250/231120-krs-01.jpg", recommend_week: 51 },
  { food_name: "クエ", category_id: 1, start_week: 2, end_week: 4, most_product_week: 3, is_rare: true, image: "https://img.hachimenroppi.com/image.php?f=CZGskqxF&adir=topic&id=809", recommend_week: 3 },
  { food_name: "ノレソレ（穴子の稚魚）", category_id: 2, start_week: 5, end_week: 6, most_product_week: 5, is_rare: true, image: "https://sakanato.jp/wp-content/uploads/2024/03/24056112_m.jpg", recommend_week: 5 },
  { food_name: "ホタルイカ", category_id: 2, start_week: 15, end_week: 17, most_product_week: 16, is_rare: false, image: "", recommend_week: nil },
  { food_name: "アカモク", category_id: 2, start_week: 16, end_week: 18, most_product_week: 17, is_rare: true, image: "https://image.rakuten.co.jp/lucas/cabinet/sozai/akamoku_1.jpg", recommend_week: 17 },
  { food_name: "サクラマス", category_id: 2, start_week: 17, end_week: 20, most_product_week: 18, is_rare: true, image: "https://www.yamagata.nmai.org/crops/umaimono/marine/images/00_05_sakuramasu_001.jpg", recommend_week: 18 },
  { food_name: "花ズッキーニ", category_id: 1, start_week: 24, end_week: 27, most_product_week: 51, is_rare: true, image: "https://recipe.organic-press.com/wp-content/uploads/2021/07/recipe_571-001.jpg", recommend_week: 25 },
  { food_name: "コシアブラ", category_id: 1, start_week: 9, end_week: 12, most_product_week: 10, is_rare: true, image: "https://media.delishkitchen.tv/article/1776/s4pka0nnj9c.jpeg?version=1751353830", recommend_week: 9 },
  { food_name: "パパイヤ", category_id: 3, start_week: 36, end_week: 45, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "マンゴー", category_id: 3, start_week: 36, end_week: 45, most_product_week: 40, is_rare: false, image: "", recommend_week: nil },
  { food_name: "ドラゴンフルーツ", category_id: 3, start_week: 30, end_week: 40, most_product_week: 35, is_rare: true, image: "https://tokubai-news-photo-production.tokubai.co.jp/c/w=1400,h=865,a=2,f=jpg/0dc9/8bc3/b978/1cef/1329/dada/d5fd/2bfb/b3ee2d1b9d5b6bdc.jpg", recommend_week: 33 },
  { food_name: "スターフルーツ", category_id: 3, start_week: 1, end_week: 14, most_product_week: 10, is_rare: true, image: "", recommend_week: nil },
  { food_name: "ブルーベリー", category_id: 3, start_week: 27, end_week: 34, most_product_week: 29, is_rare: false, image: "", recommend_week: nil },
  { food_name: "タラの芽", category_id: 1, start_week: 15, end_week: 20, most_product_week: 16, is_rare: true, image: "https://media.delishkitchen.tv/article/2805/58w5sf15r8r.jpg?version=1749458913", recommend_week: 16 },
  { food_name: "ハスカップ", category_id: 3, start_week: 28, end_week: 33, most_product_week: 29, is_rare: true, image: "https://agri.mynavi.jp/wp-content/uploads/2020/07/0889eb20dfa61af23be0327a7277cc28.jpg", recommend_week: 29 },
  { food_name: "行者ニンニク", category_id: 1, start_week: 4, end_week: 16, most_product_week: 10, is_rare: true, image: "https://www.saihok.jp/hokkaido/wp-content/uploads/2018/05/DSC06925.jpg", recommend_week: 6 },
  { food_name: "ヤブカンゾウ", category_id: 1, start_week: 8, end_week: 14, most_product_week: 10, is_rare: true, image: "https://syonai-hakusan.cocolog-nifty.com/photos/uncategorized/2009/04/10/h_030.jpg", recommend_week: 8 },
]

foods.each do |food|
  # 重複チェックして作成
  Food.find_or_create_by(food_name: food[:food_name]) do |f|
    f.attributes = food
  end
end
